### ISSUE TITLE
Custom maven config for build-image

### ISSUE THREAD

**Issue by maelstrom0x8** [dashaun/dev.dashaun.service.gateway#2]
Hello @dashaun i'm trying to configure circleci to build docker images for my spring service and push it to docker hub but it keeps failing. i know i'm missing something given that i'm relatively new to ci.

this is a snippet from my maven config.

```
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
	  <artifactId>spring-boot-maven-plugin</artifactId>
	    <executions>
	      <execution>
	        <goals>
		  <goal>build-image</goal>
		</goals>
		<configuration>
		  <image>
		    <name>maelstrom0x8/${project.name}:${project.version}</name>
		  </image>
		</configuration>
	      </execution>
	    </executions>
	  </plugin>
	</plugins>
  </build>
```

and my config.yml

```
version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0


jobs:
  build_image:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 17.0.8-amzn
      - run:
          name: "boot:build-image"
          command: "./mvnw spring-boot:build-image -DskipTests"
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/push:
          image: maelstrom0x8/order
          tag: $CIRCLE_TAG

workflows:
  build-native-image:
    jobs:
      - build_image:
          context:
            - aeros-ctx  
```
